version: 2.1
default_container: &default_container
  docker:
    - image: circleci/node:13.8.0
commands:
  restore_packages:
    steps:
      - checkout
      - restore_cache:
          key: "npm-packages"
jobs:
  build:
    <<: *default_container
    steps:
      - checkout
      - run: npm install
      - save_cache:
          paths:
            - "/home/circleci/project/node_modules"
          key: "npm-packages"
      - run: npm run lint 
  test:
    <<: *default_container
    steps:
      - restore_packages
      - run: npm run test
  analyze:
    <<: *default_container
    steps:
      - restore_packages
      - run: npm audit fix
workflows:
  my_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test